name = "EmbeddedBenchmark.jl"

[deps]
BoundingVolumeHierarchies = "df143e7c-6862-11e9-3669-9fa6f08867df"
ClosestPointSTL = "d67795cd-1ce3-49ca-af90-d17877315498"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapEmbedded = "8838a6a3-0006-4405-b874-385995508d5d"
GridapP4est = "c2c8e14b-f5fd-423d-9666-1dd9ad120af9"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
MiniQhull = "978d7f02-9e05-4691-894f-ae31a51d76ca"
P4est_wrapper = "3743d7c0-8adf-11ea-380b-7d33b0ecc1da"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
STLCutters = "284f087d-c8bb-44c4-af3c-39d0e1f330a5"
TickTock = "9ff05d80-102d-5586-aa04-3a8bd1a90d20"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TriangleIntersect = "dcd768d6-4344-5c62-a673-42b3679449b0"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
DrWatson = "2.9.1"
