name = "EmbeddedBenchmark.jl"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapEmbedded = "8838a6a3-0006-4405-b874-385995508d5d"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
MiniQhull = "978d7f02-9e05-4691-894f-ae31a51d76ca"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
STLCutters = "284f087d-c8bb-44c4-af3c-39d0e1f330a5"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
DrWatson = "2.9.1"
